Repository YNVSolutions/ynvsolutions-frontend, pull requests merged in 2025-04, with the labels that each got.

#95 Fixed the placeholder text not being shown
  app/components/contactUs.jsx
Labels: bug

#96 Added Design and Licence
  LICENCE
  ynv-structure.drawio
Labels: enhancement, Component

#98 Fixed some accessibility errors making the website more user friendly.
  app/components/contactUs.jsx
  app/components/footer.jsx
  app/components/navigation.jsx
  app/components/projects.jsx
Labels: bug, enhancement

#101 Added Team Card Component
  app/components/team.jsx
  app/page.jsx
  public/dharmendra.png
  public/jitesh.png
  public/priya.png
  public/yash.png
Labels: enhancement, Component, Feature

#102 Added Github CI Pipeline
  .github/workflows/test.yml
  app/components/team.jsx
  package-lock.json
  package.json
Labels: enhancement

#105 Created the new header component
  app/components/navigation.jsx
  app/components/team.jsx
Labels: enhancement, UI UX

#109 Linking Team Section
  app/components/navigation.jsx
Labels: bug

#111 Added major changes
  .github/workflows/api.yml
  app/components/about.jsx
  app/components/contactUs.jsx
  app/components/firebaseConfig.jsx
  app/components/header.jsx
  app/components/navigation.jsx
  app/components/serviceSection.jsx
  app/components/team.jsx
  app/page.jsx
  public/dharmendra.png
  public/jitesh.png
  public/main.mp4
  public/priya.png
  public/yash.png
Labels: bug, enhancement, Component, UI UX

#114 Added Firebase analytics
  app/components/header.jsx
  app/layout.jsx
  package-lock.json
  package.json
Labels: enhancement, Feature
