Repository YNVSolutions/ynvsolutions-frontend, pull requests merged in 2025-03, with the labels that each got.

#49 Added an expandable menu in the navigation component for smaller screens.
  app/components/navigation.jsx
Labels: enhancement

#52 Component Updates and New Feature Implementation
  app/components/clients.jsx
  app/components/contactUs.jsx
  app/components/footer.jsx
  app/components/marque.jsx
  app/components/serviceSection.jsx
  app/globals.css
  app/page.jsx
Labels: enhancement, Component

#55 Made changes to make the about section responsive.
  app/components/about.jsx
  app/components/navigation.jsx
Labels: enhancement

#60 UI improvements to navigation section
  app/components/about.jsx
  app/components/navigation.jsx
  app/globals.css
Labels: enhancement

#63 Updated Services Component Responsiveness
  app/components/serviceSection.jsx
Labels: enhancement

#64 Update Clients Components responsiveness
  README.md
  app/components/clients.jsx
Labels: enhancement

#68 Made the contact Us component responsive
  app/components/contactUs.jsx
Labels: enhancement, Feature

#71 Updation on services component
  app/components/marque.jsx
  app/components/navigation.jsx
  app/components/serviceSection.jsx
  app/page.jsx
Labels: enhancement, Feature, UI UX

#73 Updated the Client Component
  app/components/clients.jsx
  app/components/portfolio.jsx
  app/components/projects.jsx
Labels: enhancement, Feature, UI UX

#77 Created some UI updates on Footer Component
  app/components/about.jsx
  app/components/footer.jsx
  app/page.jsx
  public/back.png
Labels: enhancement

#76 Added visual feedback to navigation links.
  app/components/navigation.jsx
Labels: enhancement, UI UX

#79 Changed the client logos and other minor tweaks to the client section.
  app/components/clients.jsx
  public/ARX_vision.png
  public/Dona-logo.svg
  public/Dona.png
  public/Our_media.png
  public/arxVisionLogo.jpg
  public/ourMedia.png
Labels: enhancement, UI UX

#80 Updated The About Component Completely
  app/components/about.jsx
  app/components/serviceSection.jsx
  app/page.jsx
Labels: enhancement, Feature, UI UX

#81 Few layout changes
  app/components/about.jsx
  app/globals.css
Labels: bug

#82 Updated Project and About Component
  app/components/about.jsx
  app/components/projects.jsx
Labels: bug, enhancement, UI UX

#84 Changes for layout on smaller screens
  app/components/contactUs.jsx
  app/components/navigation.jsx
  app/components/serviceSection.jsx
Labels: enhancement

#85 Update Main Component
  app/components/about.jsx
  app/globals.css
  app/layout.jsx
Labels: bug, enhancement, Feature, UI UX

#86 Redesigned projects section.
  app/components/projects.jsx
  public/Arx_vision_ss.png
  public/Dona_ss.png
  public/Our_media_ss.png
Labels: enhancement, Component, UI UX

#88 Updation of Services component
  app/components/serviceSection.jsx
  public/ai.gif
  public/app.gif
  public/mdm.gif
  public/web.gif
Labels: enhancement, Component, UI UX

#89 Made some UI and bug fixes
  app/components/about.jsx
  app/components/clients.jsx
  app/components/navigation.jsx
  app/components/projects.jsx
  app/components/serviceSection.jsx
  app/globals.css
  public/Dona.png
  public/arx.png
  public/ourMedia.webp
Labels: enhancement, UI UX

#91 Updation in Contact Component
  app/components/contactUs.jsx
  app/components/firebaseConfig.jsx
  package-lock.json
  package.json
Labels: enhancement, Feature
